name: ChatDisplayNameChanger
version: 1.0
main: com.masakun.chatdisplay.ChatDisplayNameChanger
api-version: 1.20
commands:
  cdname:
    description: Change your chat display name
    usage: /cdname <name>
